#!/bin/bash

echo "🔧 Fixing failed migration in Railway database"
echo ""
echo "Option 1: Mark migration as resolved using Railway CLI"
echo "========================================================="
echo ""
echo "Copy and paste this command in your terminal:"
echo ""
echo "cd /Users/johnmichaelobligar/Documents/Development/Otico/backend && railway run --service backend npx prisma migrate resolve --applied 20251028200841_add_door_is_locked_field"
echo ""
echo ""
echo "Option 2: Run SQL directly via psql"
echo "====================================="
echo ""
echo "1. Get the Railway PostgreSQL connection URL from the dashboard"
echo "2. Run this command (replace <DATABASE_URL> with actual URL):"
echo ""
echo "psql '<DATABASE_URL>' -c \"UPDATE _prisma_migrations SET finished_at = NOW(), applied_steps_count = 1 WHERE migration_name = '20251028200841_add_door_is_locked_field';\""
echo ""
echo ""
echo "Option 3: Use Railway Dashboard SQL Console"
echo "============================================="
echo ""
echo "1. Go to Railway Dashboard → Postgres service"
echo "2. Click 'Data' tab"
echo "3. Click 'Query' button"
echo "4. Paste this SQL:"
echo ""
cat resolve-migration.sql
echo ""
echo "5. Click 'Run Query'"
echo ""
echo "After running any of these options, Railway will automatically redeploy."
